### ISSUE TITLE
No public methods have @Subscribe annotation...

### ISSUE THREAD

**Issue by kcorey** [greenrobot/EventBus#251]
Following the getting-started guidelines on an existing project, I've run into an error (shown below).

The code for my app where I'm expecting this to work starts LoadingActivity as the first Activity of my app:

`import com.google.common.eventbus.Subscribe;

import org.greenrobot.eventbus.EventBus;

import io.fabric.sdk.android.Fabric;

public class LoadingActivity extends BaseActivity implements AlertDialogButtonListener {
    AlertDialog mDialog = null;
    AlertDialog mPushDialog = null;

    @Subscribe
    public void onMessageEvent(MessageEvent event){
        Toast.makeText(this, "From Loading "+event.message, Toast.LENGTH_SHORT).show();
    }

    @Override
    public void onStart() {
        super.onStart();
        EventBus.getDefault().register(this);
    }

    @Override
    public void onStop() {
        EventBus.getDefault().unregister(this);
        super.onStop();
    }

`
As you can see, I /do/ have @Subscribe annotation.  Everything compiles without issue, but when run results in:
`02-09 09:47:05.393 25859-25859/com.crowdlab.live E/Fabric: Failed to execute task.
                                                           java.util.concurrent.TimeoutException
                                                               at java.util.concurrent.FutureTask.get(FutureTask.java:176)
                                                               at com.crashlytics.android.CrashlyticsExecutorServiceWrapper.executeSyncLoggingException(CrashlyticsExecutorServiceWrapper.java:44)
                                                               at com.crashlytics.android.CrashlyticsUncaughtExceptionHandler.uncaughtException(CrashlyticsUncaughtExceptionHandler.java:274)
                                                               at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
                                                               at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
02-09 09:47:05.393 25859-25859/com.crowdlab.live E/AndroidRuntime: FATAL EXCEPTION: main
                                                                   Process: com.crowdlab.live, PID: 25859
                                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.crowdlab.live/com.crowdlab.activities.LoadingActivity}: org.greenrobot.eventbus.EventBusException: Subscriber class com.crowdlab.activities.LoadingActivity and its super classes have no public methods with the @Subscribe annotation
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3119)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3218)
                                                                       at android.app.ActivityThread.access$1000(ActivityThread.java:198)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1676)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:145)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6837)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
                                                                    Caused by: org.greenrobot.eventbus.EventBusException: Subscriber class com.crowdlab.activities.LoadingActivity and its super classes have no public methods with the @Subscribe annotation
                                                                       at org.greenrobot.eventbus.SubscriberMethodFinder.findSubscriberMethods(SubscriberMethodFinder.java:67)
                                                                       at org.greenrobot.eventbus.EventBus.register(EventBus.java:136)
                                                                       at com.crowdlab.activities.LoadingActivity.onStart(LoadingActivity.java:35)
`

I'm not using ProGuard.

Any ideas what could be going on?  Is it a bug?  Is it a bogus installation?

-Ken

**Comment by kcorey** [comment]
Turns out I'd let the IDE choose Google's EventBus Subscribe rather than GreenRobot's.  

The error should probably read "no methods implementing the com.greenrobot.eventbus @Subscribe annotation".
