### ISSUE TITLE
Import to eclipse JUNO ,exception happens at rumtime

### ISSUE THREAD

**Issue by ZionPi** [greenrobot/EventBus#257]
```
02-17 14:03:00.443: W/System.err(12026): java.lang.NoClassDefFoundError: Failed resolution of: Lorg/greenrobot/eventbus/EventBus;


02-17 14:03:00.443: W/System.err(12026): Caused by: java.lang.ClassNotFoundException: Didn't find class "org.greenrobot.eventbus.EventBus" on path: DexPathList[[zip file "/data/app/com.example.demo-1/base.apk"],nativeLibraryDirectories=[/data/app/com.example.demo-1/lib/arm, /vendor/lib, /system/lib]]
02-17 14:03:00.443: W/System.err(12026): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
02-17 14:03:00.443: W/System.err(12026): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
02-17 14:03:00.443: W/System.err(12026): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
02-17 14:03:00.443: W/System.err(12026): 	... 16 more
02-17 14:03:00.443: W/System.err(12026): 	Suppressed: java.lang.ClassNotFoundException: org.greenrobot.eventbus.EventBus
02-17 14:03:00.443: W/System.err(12026): 		at java.lang.Class.classForName(Native Method)
02-17 14:03:00.443: W/System.err(12026): 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
02-17 14:03:00.443: W/System.err(12026): 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
02-17 14:03:00.443: W/System.err(12026): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
02-17 14:03:00.443: W/System.err(12026): 		... 17 more
02-17 14:03:00.443: W/System.err(12026): 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
```

**Comment by ZionPi** [comment]
Java compiler compliance level is 1.6

**Comment by ZionPi** [comment]
Warning from **Console**
```
[2016-02-17 14:30:12 - Demo] Dx 
trouble processing:
[2016-02-17 14:30:12 - Demo] Dx bad class file magic (cafebabe) or version (0033.0000)
...while parsing org/greenrobot/eventbus/AsyncPoster.class
...while processing org/greenrobot/eventbus/AsyncPoster.class
[2016-02-17 14:30:12 - Demo] Dx 
trouble processing:
[2016-02-17 14:30:12 - Demo] Dx bad class file magic (cafebabe) or version (0033.0000)
...while parsing org/greenrobot/eventbus/BackgroundPoster.class
...while processing org/greenrobot/eventbus/BackgroundPoster.class
[2016-02-17 14:30:12 - Demo] Dx 
trouble processing:
[2016-02-17 14:30:12 - Demo] Dx bad class file magic (cafebabe) or version (0033.0000)
...while parsing org/greenrobot/eventbus/EventBus$1.class
...while processing org/greenrobot/eventbus/EventBus$1.class
[2016-02-17 14:30:12 - Demo] Dx 
trouble processing:
[2016-02-17 14:30:12 - Demo] Dx bad class file magic (cafebabe) or version (0033.0000)
...while parsing org/greenrobot/eventbus/EventBus$2.class
...while processing org/greenrobot/eventbus/EventBus$2.class
[2016-02-17 14:30:12 - Demo] Dx 
trouble processing:
[2016-02-17 14:30:12 - Demo] Dx bad class file magic (cafebabe) or version (0033.0000)
...while parsing org/greenrobot/eventbus/EventBus$PostCallback.class
...while processing org/greenrobot/eventbus/EventBus$PostCallback.class
[2016-02-17 14:30:12 - Demo] Dx 
trouble processing:
[2016-02-17 14:30:12 - Demo] Dx bad class file magic (cafebabe) or version (0033.0000)
...while parsing org/greenrobot/eventbus/EventBus$PostingThreadState.class
...while processing org/greenrobot/eventbus/EventBus$PostingThreadState.class
[2016-02-17 14:30:12 - Demo] Dx 
trouble processing:
[2016-02-17 14:30:12 - Demo] Dx bad class file magic (cafebabe) or version (0033.0000)
...while parsing org/greenrobot/eventbus/EventBus.class
...while processing org/greenrobot/eventbus/EventBus.class
[2016-02-17 14:30:12 - Demo] Dx 
trouble processing:
[2016-02-17 14:30:12 - Demo] Dx bad class file magic (cafebabe) or version (0033.0000)
...while parsing org/greenrobot/eventbus/EventBusBuilder.class
...while processing org/greenrobot/eventbus/EventBusBuilder.class
[2016-02-17 14:30:12 - Demo] Dx 
trouble processing:
[2016-02-17 14:30:12 - Demo] Dx bad class file magic (cafebabe) or version (0033.0000)
...while parsing org/greenrobot/eventbus/EventBusException.class
...while processing org/greenrobot/eventbus/EventBusException.class
[2016-02-17 14:30:12 - Demo] Dx 
trouble processing:
[2016-02-17 14:30:12 - Demo] Dx bad class file magic (cafebabe) or version (0033.0000)
...while parsing org/greenrobot/eventbus/HandlerPoster.class
...while processing org/greenrobot/eventbus/HandlerPoster.class
[2016-02-17 14:30:12 - Demo] Dx 
trouble processing:
[2016-02-17 14:30:12 - Demo] Dx bad class file magic (cafebabe) or version (0033.0000)
...while parsing org/greenrobot/eventbus/meta/AbstractSubscriberInfo.class
...while processing org/greenrobot/eventbus/meta/AbstractSubscriberInfo.class
[2016-02-17 14:30:12 - Demo] Dx 
trouble processing:
[2016-02-17 14:30:12 - Demo] Dx bad class file magic (cafebabe) or version (0033.0000)
...while parsing org/greenrobot/eventbus/meta/SimpleSubscriberInfo.class
...while processing org/greenrobot/eventbus/meta/SimpleSubscriberInfo.class
[2016-02-17 14:30:12 - Demo] Dx 
trouble processing:
[2016-02-17 14:30:12 - Demo] Dx bad class file magic (cafebabe) or version (0033.0000)
...while parsing org/greenrobot/eventbus/meta/SubscriberInfo.class
...while processing org/greenrobot/eventbus/meta/SubscriberInfo.class
[2016-02-17 14:30:12 - Demo] Dx 
trouble processing:
[2016-02-17 14:30:12 - Demo] Dx bad class file magic (cafebabe) or version (0033.0000)
...while parsing org/greenrobot/eventbus/meta/SubscriberInfoIndex.class
...while processing org/greenrobot/eventbus/meta/SubscriberInfoIndex.class
[2016-02-17 14:30:12 - Demo] Dx 
trouble processing:
[2016-02-17 14:30:12 - Demo] Dx bad class file magic (cafebabe) or version (0033.0000)
...while parsing org/greenrobot/eventbus/meta/SubscriberMethodInfo.class
...while processing org/greenrobot/eventbus/meta/SubscriberMethodInfo.class
[2016-02-17 14:30:12 - Demo] Dx 
trouble processing:
[2016-02-17 14:30:12 - Demo] Dx bad class file magic (cafebabe) or version (0033.0000)
...while parsing org/greenrobot/eventbus/NoSubscriberEvent.class
...while processing org/greenrobot/eventbus/NoSubscriberEvent.class
[2016-02-17 14:30:12 - Demo] Dx 
trouble processing:
[2016-02-17 14:30:12 - Demo] Dx bad class file magic (cafebabe) or version (0033.0000)
...while parsing org/greenrobot/eventbus/PendingPost.class
...while processing org/greenrobot/eventbus/PendingPost.class
[2016-02-17 14:30:12 - Demo] Dx 
trouble processing:
[2016-02-17 14:30:12 - Demo] Dx bad class file magic (cafebabe) or version (0033.0000)
...while parsing org/greenrobot/eventbus/PendingPostQueue.class
...while processing org/greenrobot/eventbus/PendingPostQueue.class
[2016-02-17 14:30:12 - Demo] Dx 
trouble processing:
[2016-02-17 14:30:12 - Demo] Dx bad class file magic (cafebabe) or version (0033.0000)
...while parsing org/greenrobot/eventbus/Subscribe.class
...while processing org/greenrobot/eventbus/Subscribe.class
[2016-02-17 14:30:12 - Demo] Dx 
trouble processing:
[2016-02-17 14:30:12 - Demo] Dx bad class file magic (cafebabe) or version (0033.0000)
...while parsing org/greenrobot/eventbus/SubscriberExceptionEvent.class
...while processing org/greenrobot/eventbus/SubscriberExceptionEvent.class
[2016-02-17 14:30:12 - Demo] Dx 
trouble processing:
[2016-02-17 14:30:12 - Demo] Dx bad class file magic (cafebabe) or version (0033.0000)
...while parsing org/greenrobot/eventbus/SubscriberMethod.class
...while processing org/greenrobot/eventbus/SubscriberMethod.class
[2016-02-17 14:30:12 - Demo] Dx 
trouble processing:
[2016-02-17 14:30:12 - Demo] Dx bad class file magic (cafebabe) or version (0033.0000)
...while parsing org/greenrobot/eventbus/SubscriberMethodFinder$FindState.class
...while processing org/greenrobot/eventbus/SubscriberMethodFinder$FindState.class
[2016-02-17 14:30:12 - Demo] Dx 
trouble processing:
[2016-02-17 14:30:12 - Demo] Dx bad class file magic (cafebabe) or version (0033.0000)
...while parsing org/greenrobot/eventbus/SubscriberMethodFinder.class
...while processing org/greenrobot/eventbus/SubscriberMethodFinder.class
[2016-02-17 14:30:12 - Demo] Dx 
trouble processing:
[2016-02-17 14:30:12 - Demo] Dx bad class file magic (cafebabe) or version (0033.0000)
...while parsing org/greenrobot/eventbus/Subscription.class
...while processing org/greenrobot/eventbus/Subscription.class
[2016-02-17 14:30:12 - Demo] Dx 
trouble processing:
[2016-02-17 14:30:12 - Demo] Dx bad class file magic (cafebabe) or version (0033.0000)
...while parsing org/greenrobot/eventbus/ThreadMode.class
...while processing org/greenrobot/eventbus/ThreadMode.class
[2016-02-17 14:30:12 - Demo] Dx 
trouble processing:
[2016-02-17 14:30:12 - Demo] Dx bad class file magic (cafebabe) or version (0033.0000)
...while parsing org/greenrobot/eventbus/util/AsyncExecutor$1.class
...while processing org/greenrobot/eventbus/util/AsyncExecutor$1.class
[2016-02-17 14:30:12 - Demo] Dx 
trouble processing:
[2016-02-17 14:30:12 - Demo] Dx bad class file magic (cafebabe) or version (0033.0000)
...while parsing org/greenrobot/eventbus/util/AsyncExecutor$Builder.class
...while processing org/greenrobot/eventbus/util/AsyncExecutor$Builder.class
[2016-02-17 14:30:12 - Demo] Dx 
trouble processing:
[2016-02-17 14:30:12 - Demo] Dx bad class file magic (cafebabe) or version (0033.0000)
...while parsing org/greenrobot/eventbus/util/AsyncExecutor$RunnableEx.class
...while processing org/greenrobot/eventbus/util/AsyncExecutor$RunnableEx.class
[2016-02-17 14:30:12 - Demo] Dx 
trouble processing:
[2016-02-17 14:30:12 - Demo] Dx bad class file magic (cafebabe) or version (0033.0000)
...while parsing org/greenrobot/eventbus/util/AsyncExecutor.class
...while processing org/greenrobot/eventbus/util/AsyncExecutor.class
[2016-02-17 14:30:12 - Demo] Dx 
trouble processing:
[2016-02-17 14:30:12 - Demo] Dx bad class file magic (cafebabe) or version (0033.0000)
...while parsing org/greenrobot/eventbus/util/ErrorDialogConfig.class
...while processing org/greenrobot/eventbus/util/ErrorDialogConfig.class
[2016-02-17 14:30:12 - Demo] Dx 
trouble processing:
[2016-02-17 14:30:12 - Demo] Dx bad class file magic (cafebabe) or version (0033.0000)
...while parsing org/greenrobot/eventbus/util/ErrorDialogFragmentFactory$Honeycomb.class
...while processing org/greenrobot/eventbus/util/ErrorDialogFragmentFactory$Honeycomb.class
[2016-02-17 14:30:12 - Demo] Dx 
trouble processing:
[2016-02-17 14:30:12 - Demo] Dx bad class file magic (cafebabe) or version (0033.0000)
...while parsing org/greenrobot/eventbus/util/ErrorDialogFragmentFactory$Support.class
...while processing org/greenrobot/eventbus/util/ErrorDialogFragmentFactory$Support.class
[2016-02-17 14:30:12 - Demo] Dx 
trouble processing:
[2016-02-17 14:30:12 - Demo] Dx bad class file magic (cafebabe) or version (0033.0000)
...while parsing org/greenrobot/eventbus/util/ErrorDialogFragmentFactory.class
...while processing org/greenrobot/eventbus/util/ErrorDialogFragmentFactory.class
[2016-02-17 14:30:12 - Demo] Dx 
trouble processing:
[2016-02-17 14:30:12 - Demo] Dx bad class file magic (cafebabe) or version (0033.0000)
...while parsing org/greenrobot/eventbus/util/ErrorDialogFragments$Honeycomb.class
...while processing org/greenrobot/eventbus/util/ErrorDialogFragments$Honeycomb.class
[2016-02-17 14:30:12 - Demo] Dx 
trouble processing:
[2016-02-17 14:30:12 - Demo] Dx bad class file magic (cafebabe) or version (0033.0000)
...while parsing org/greenrobot/eventbus/util/ErrorDialogFragments$Support.class
...while processing org/greenrobot/eventbus/util/ErrorDialogFragments$Support.class
[2016-02-17 14:30:12 - Demo] Dx 
trouble processing:
[2016-02-17 14:30:12 - Demo] Dx bad class file magic (cafebabe) or version (0033.0000)
...while parsing org/greenrobot/eventbus/util/ErrorDialogFragments.class
...while processing org/greenrobot/eventbus/util/ErrorDialogFragments.class
[2016-02-17 14:30:12 - Demo] Dx 
trouble processing:
[2016-02-17 14:30:12 - Demo] Dx bad class file magic (cafebabe) or version (0033.0000)
...while parsing org/greenrobot/eventbus/util/ErrorDialogManager$HoneycombManagerFragment.class
...while processing org/greenrobot/eventbus/util/ErrorDialogManager$HoneycombManagerFragment.class
[2016-02-17 14:30:12 - Demo] Dx 
trouble processing:
[2016-02-17 14:30:12 - Demo] Dx bad class file magic (cafebabe) or version (0033.0000)
...while parsing org/greenrobot/eventbus/util/ErrorDialogManager$SupportManagerFragment.class
...while processing org/greenrobot/eventbus/util/ErrorDialogManager$SupportManagerFragment.class
[2016-02-17 14:30:12 - Demo] Dx 
trouble processing:
[2016-02-17 14:30:12 - Demo] Dx bad class file magic (cafebabe) or version (0033.0000)
...while parsing org/greenrobot/eventbus/util/ErrorDialogManager.class
...while processing org/greenrobot/eventbus/util/ErrorDialogManager.class
[2016-02-17 14:30:12 - Demo] Dx 
trouble processing:
[2016-02-17 14:30:12 - Demo] Dx bad class file magic (cafebabe) or version (0033.0000)
...while parsing org/greenrobot/eventbus/util/ExceptionToResourceMapping.class
...while processing org/greenrobot/eventbus/util/ExceptionToResourceMapping.class
[2016-02-17 14:30:12 - Demo] Dx 
trouble processing:
[2016-02-17 14:30:12 - Demo] Dx bad class file magic (cafebabe) or version (0033.0000)
...while parsing org/greenrobot/eventbus/util/HasExecutionScope.class
...while processing org/greenrobot/eventbus/util/HasExecutionScope.class
[2016-02-17 14:30:12 - Demo] Dx 
trouble processing:
[2016-02-17 14:30:12 - Demo] Dx bad class file magic (cafebabe) or version (0033.0000)
...while parsing org/greenrobot/eventbus/util/ThrowableFailureEvent.class
...while processing org/greenrobot/eventbus/util/ThrowableFailureEvent.class

```
