### ISSUE TITLE
java.lang.NoClassDefFoundError: org.greenrobot.eventbus.EventBus$1

### ISSUE THREAD

**Issue by kargm** [greenrobot/EventBus#282]
Hi guys, 

I'm using Eventbus 3 with subscriber index on a simple app to communicate between activities. While on most devices, this works fine, strangely on a LG Optimus L7 II (vee7e) with Android 4.1, i get the following error:

```
java.lang.NoClassDefFoundError: org.greenrobot.eventbus.EventBus$1
	at org.greenrobot.eventbus.EventBus.<init>(EventBus.java:55)
	at org.greenrobot.eventbus.EventBus.<init>(EventBus.java:104)
	at org.greenrobot.eventbus.EventBus.getDefault(EventBus.java:82)
	at com.thehighscore.kargm.thehighscore.MyActivity.onCreate(MyActivity.java:67)
	at android.app.Activity.performCreate(Activity.java:5254)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1082)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2038)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2099)
	at android.app.ActivityThread.access$600(ActivityThread.java:138)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1205)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:4929)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:798)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:565)
	at dalvik.system.NativeStart.main(Native Method)
```

I already checked th FAQ and saw the related article "A java.lang.NoClassDefFoundError is thrown when a subscriber class is registered. What can I do?". So I switched to subscriber index, but the problem seems to persist... 

Any ideas?

**Comment by greenrobot-team** [comment]
You should check out this [Stackoverflow comment](http://stackoverflow.com/a/17974068).

It might be possible that this device includes EventBus on its classpath by default. The only solution I can think of is to obfuscate EventBus with ProGuard so it is named differently.
