### ISSUE TITLE
I found these two tools can't work at the same time

### ISSUE THREAD

**Issue by Lnybb** [greenrobot/EventBus#309]
These two tools are ‘com.jakewharton:butterknife:8.0.1’ and 'org.greenrobot:eventbus:3.0.0'.
Particular case is such, butterknife will be submitted to the null pointer.
I am a student in China, English is not very good, please forgive me.

**Comment by william-ferguson-au** [comment]
You are going to need to explain your problem more clearly.
Perhaps you could show some code.

**Comment by Lnybb** [comment]
This is my code.

`public class AActivity extends AppCompatActivity {

    private static final String TAG = "AActivity";

    @InjectView(R.id.tv)
    TextView tv;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_a);
        ButterKnife.inject(this);
        EventBus.getDefault().register(this);
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        EventBus.getDefault().unregister(this);
    }

    public void openBActivity(View view) {
        Intent intent = new Intent(this, BActivity.class);
        startActivity(intent);
    }

    @Subscribe(threadMode = ThreadMode.MAIN)
    public void onUseEvent(String s) {
        Log.d(TAG, "onUseEvent: " + s);
        tv.setText(s);
        Toast.makeText(this, s, Toast.LENGTH_SHORT).show();
    }
}`
`public class BActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_b);
    }

    public void backBActivity(View view) {
        EventBus.getDefault().post("data");
        this.finish();
    }
}`
`EventBus: Could not dispatch event: class java.lang.String to subscribing class class com.zyd.eventbus.AActivity
                                                            java.lang.NullPointerException
                                                                at com.zyd.eventbus.AActivity.onUseEvent(AActivity.java:47)
                                                                at java.lang.reflect.Method.invokeNative(Native Method)
                                                                at java.lang.reflect.Method.invoke(Method.java:515)
                                                                at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:485)
                                                                at org.greenrobot.eventbus.EventBus.postToSubscription(EventBus.java:420)
                                                                at org.greenrobot.eventbus.EventBus.postSingleEventForEventType(EventBus.java:397)
                                                                at org.greenrobot.eventbus.EventBus.postSingleEvent(EventBus.java:370)
                                                                at org.greenrobot.eventbus.EventBus.post(EventBus.java:251)
                                                                at com.zyd.eventbus.BActivity.backBActivity(BActivity.java:18)
                                                                at java.lang.reflect.Method.invokeNative(Native Method)
                                                                at java.lang.reflect.Method.invoke(Method.java:515)
                                                                at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:284)
                                                                at android.view.View.performClick(View.java:4438)
                                                                at android.view.View$PerformClick.run(View.java:18422)
                                                                at android.os.Handler.handleCallback(Handler.java:733)
                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                at android.os.Looper.loop(Looper.java:136)
                                                                at android.app.ActivityThread.main(ActivityThread.java:5045)
                                                                at java.lang.reflect.Method.invokeNative(Native Method)
                                                                at java.lang.reflect.Method.invoke(Method.java:515)
                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                                                                at dalvik.system.NativeStart.main(Native Method)`

But when I replace butterknife  version 5.1.1,they can work again.

use this " compile 'com.jakewharton:butterknife:5.1.1' "

**Comment by william-ferguson-au** [comment]
Sounds like a bug with ButterKnife.

**Comment by guidedways** [comment]
Any luck? Not sure if I've got the same issue but EventBus is working fine on a Android 6.0 while on 5.1.1 the subscribers aren't receiving any events (I'm using Butterknife too separately)

**Comment by Lnybb** [comment]
I now use ‘ButterKnife’ version is 5.1.1,it in the android version 5.0 working properly.Maybe you can try some other ‘ButterKnife’ version.

**Comment by greenrobot-team** [comment]
When calling `EventBus.getDefault().post("data");` in `BActivity` there is no guarantee that the views of `AActivity` or the activity itself still exist.

To communicate across activity boundaries you probably should use something like [startActivityForResult()](https://developer.android.com/training/basics/intents/result.html).
