### ISSUE TITLE
IncompatibleClassChangeError: Couldn't find org.greenrobot.eventbus.Subscribe.threadMode

### ISSUE THREAD

**Issue by whiteLT** [greenrobot/EventBus#319]
```
Fatal Exception: java.lang.IncompatibleClassChangeError: Couldn't find org.greenrobot.eventbus.Subscribe.threadMode
       at libcore.reflect.AnnotationAccess.toAnnotationInstance(AnnotationAccess.java:659)
       at libcore.reflect.AnnotationAccess.toAnnotationInstance(AnnotationAccess.java:641)
       at libcore.reflect.AnnotationAccess.getDeclaredAnnotation(AnnotationAccess.java:170)
       at java.lang.reflect.Method.getAnnotation(Method.java:301)
       at org.greenrobot.eventbus.SubscriberMethodFinder.findUsingReflectionInSingleClass(SubscriberMethodFinder.java:165)
       at org.greenrobot.eventbus.SubscriberMethodFinder.findUsingInfo(SubscriberMethodFinder.java:88)
       at org.greenrobot.eventbus.SubscriberMethodFinder.findSubscriberMethods(SubscriberMethodFinder.java:64)
       at org.greenrobot.eventbus.EventBus.register(EventBus.java:136)
       at lt.lemonlabs.android.paysera.common.PayseraApplication.initializeEventBus(PayseraApplication.java:179)
       at lt.lemonlabs.android.paysera.common.PayseraApplication.onCreate(PayseraApplication.java:87)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1020)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5007)
       at android.app.ActivityThread.access$1600(ActivityThread.java:172)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1483)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:5832)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
```

EventBus 3.0.0
Android 5.0 - 5.0.2
Hello, I get this crash randomly for some users. Is there any solution for this one or more information?

**Comment by greenrobot-team** [comment]
I assume this may happen if your code was not properly recompiled against the new EventBus. See this [Stackoverflow post about IncompatibleClassChangeError](http://stackoverflow.com/questions/1980452/what-causes-java-lang-incompatibleclasschangeerror).

**Comment by vytautasgimbutas** [comment]
Hi,
i'm quite sure that the project build was at least fully cleaned. Why it's happening only on 5.0 - 5.0.2 android? Maybe a link to Crashlytics will help: http://crashes.to/s/7a9918f4360?

**Comment by greenrobot-team** [comment]
[Others see this problem](https://github.com/google/gson/issues/726) for some Samsung devices as well.

Did you check that [ProGuard does not remove the annotations](http://greenrobot.org/eventbus/documentation/proguard/)?

**Comment by vytautasgimbutas** [comment]
We don't use proguard.

**Comment by greenrobot-team** [comment]
Well, then as linked above this is likely a bug with the firmware on those specific Samsung devices. So no change in EventBus can fix this, it will require a fix by Samsung.

Not aware of a work around either :(

**Comment by etp404** [comment]
Hello,

Could I quickly check that there's been no change on this stance? We're seeing this issue and it seems like there's nothing we could do on our end to mitigate it.

Cheers,
Matt

**Comment by greenrobot-team** [comment]
@etp404 Sorry, have no new info about this issue. -ut

**Comment by AndroidDeveloperLB** [comment]
@greenrobot-team I got this issue today. This is the logs on Crashlytics:

```
Fatal Exception: java.lang.IncompatibleClassChangeError: Couldn't find org.greenrobot.eventbus.a.threadMode
       at libcore.reflect.AnnotationAccess.toAnnotationInstance(AnnotationAccess.java:659)
       at libcore.reflect.AnnotationAccess.toAnnotationInstance(AnnotationAccess.java:641)
       at libcore.reflect.AnnotationAccess.getDeclaredAnnotation(AnnotationAccess.java:170)
       at java.lang.reflect.Method.getAnnotation(Method.java:301)
       at org.greenrobot.eventbus.SubscriberMethodFinder.findUsingReflectionInSingleClass(SubscriberMethodFinder.java:175)
       at org.greenrobot.eventbus.SubscriberMethodFinder.findUsingInfo(SubscriberMethodFinder.java:88)
       at org.greenrobot.eventbus.SubscriberMethodFinder.findSubscriberMethods(SubscriberMethodFinder.java:64)
       at org.greenrobot.eventbus.EventBus.register(EventBus.java:143)
...
```

And indeed it happens on Android 5.0 (Samsung Galaxy Note3).
I use this version of the library:

```
    implementation 'org.greenrobot:eventbus:3.2.0'
```

It's quite a rare bug though. I think I might have seen it in the past, but now it's a single case on Crashlytics.

Maybe it's only on Android 5 ?
