### ISSUE TITLE
FATAL EXCEPTION: main    java.lang.NoClassDefFoundError: org.greenrobot.eventbus.EventBusBuilder                                                                       at org.greenrobot.eventbus.EventBus.<clinit>(EventBus.java:48)

### ISSUE THREAD

**Issue by liu-hailin** [greenrobot/EventBus#321]
FATAL EXCEPTION: main
                                                                  java.lang.NoClassDefFoundError: org.greenrobot.eventbus.EventBusBuilder
                                                                      at org.greenrobot.eventbus.EventBus.<clinit>(EventBus.java:48)
                                                                      at com.ejlchina.ejl.ui.frag.MyMicroHomeFrag.onCreate(MyMicroHomeFrag.java:128)
                                                                      at android.support.v4.app.Fragment.performCreate(Fragment.java:2062)
                                                                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1051)
                                                                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1286)
                                                                      at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:758)
                                                                      at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1671)
                                                                      at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:532)
                                                                      at android.os.Handler.handleCallback(Handler.java:725)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                      at android.os.Looper.loop(Looper.java:153)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5297)
                                                                      at java.lang.reflect.Method.invokeNative(Native Method)
                                                                      at java.lang.reflect.Method.invoke(Method.java:511)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
                                                                      at dalvik.system.NativeStart.main(Native Method)

**Comment by liu-hailin** [comment]
不混淆代码报的错  混淆了一样

**Comment by liu-hailin** [comment]
自己项目MultiDex出错了     请关闭

**Comment by wuseal** [comment]
@liu-hailin @I also have this problem with out proguard,what reason could be ,if I set muiltiDex to true in Android  Studio,wheather it may happened?
