### ISSUE TITLE
java.lang.NoClassDefFoundError: android/os/PersistableBundle pre L

### ISSUE THREAD

**Issue by DJafari** [greenrobot/EventBus#324]
```
java.lang.NoClassDefFoundError: android/os/PersistableBundle
at java.lang.Class.getDeclaredMethods(Native Method)
at java.lang.Class.getPublicMethodsRecursive(Class.java:955)
at java.lang.Class.getMethods(Class.java:938)
at org.greenrobot.eventbus.SubscriberMethodFinder.findUsingReflectionInSingleClass(SubscriberMethodFinder.java:157)
at org.greenrobot.eventbus.SubscriberMethodFinder.findUsingInfo(SubscriberMethodFinder.java:88)
at org.greenrobot.eventbus.SubscriberMethodFinder.findSubscriberMethods(SubscriberMethodFinder.java:64)
at org.greenrobot.eventbus.EventBus.register(EventBus.java:136)
at MainActivity.onResume(MainActivity.java:240)
```

what is problem ?
on api +21 is ok, but pre 21 throw above crash .

**Comment by greenrobot-team** [comment]
Take a look at [the FAQ](http://greenrobot.org/eventbus/documentation/faq/).

**Comment by DJafari** [comment]
ok thanks
