### ISSUE TITLE
 java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation

### ISSUE THREAD

**Issue by Andoctorey** [greenrobot/EventBus#406]
Receive crashes on production users:
```
Fatal Exception: java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation
       at java.lang.reflect.Method.getAnnotation(Method.java)
       at java.lang.reflect.Method.getAnnotation(Method.java:266)
       at org.greenrobot.eventbus.SubscriberMethodFinder.findUsingReflectionInSingleClass(Unknown Source:165)
       at org.greenrobot.eventbus.SubscriberMethodFinder.findUsingInfo(Unknown Source:88)
       at org.greenrobot.eventbus.SubscriberMethodFinder.findSubscriberMethods(Unknown Source:64)
       at org.greenrobot.eventbus.EventBus.register(Unknown Source:136)
       at com.*****.BaseActivity.onResume(Unknown Source:73)
       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1192)
       at android.app.Activity.performResume(Activity.java:5364)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2924)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3042)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2337)
       at android.app.ActivityThread.access$800(ActivityThread.java:184)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1280)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5281)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:791)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:607)
       at dalvik.system.NativeStart.main(NativeStart.java)
```
Code:
```
 @Override
    protected void onResume() {
        super.onResume();
            if (!EventBus.getDefault().isRegistered(this)) {
                EventBus.getDefault().register(this); //crash is here
            }
    }
```
Dexguard:
```
-keepattributes JavascriptInterface
-keepclassmembers class * {
    @android.webkit.JavascriptInterface <methods>;
}
```

Eventbus version - 3.0.0
For now have only 5 crashes, 3 users. Android: 4.1.2, 4.4.2. Devices: Sony Xperia GX, Kyocera TORQUE G01, Fujitsu F-01F

**Comment by greenrobot-team** [comment]
`java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation` indicates that the class (one of your classes that contains a `@Subscribed` annotation) in question seems to be different in your final APK (specifically the dex file).

This may be related to multi-dex or if you somehow include these classes twice as a dependency.
-ut

**Comment by Andoctorey** [comment]
Thanks. Probably found problem. We rewrote EventBusBuilder and EventBus classes, added some logs. EventBusBuilder constructor is not public, se we put custom classes in `org.greenrobot.eventbus` package.  Maybe it caused problem.

**Comment by greenrobot-team** [comment]
Alright, closing this then. -ut

**Comment by BornLotus** [comment]
Now, I faced the same problem as above,can you tell me why and what I should do with it? thanks a lot

**Comment by DeanKersting** [comment]
> Now, I faced the same problem as above,can you tell me why and what I should do with it? thanks a lot

This is usually happened when call Eventbus.register(subscribe)，subscribe Class is belonged to a different dex which is not THE dex Eventbus class belonged to!So you can add Eventbus ref(such as Eventbus.class.getName()) in your subscribe class to prevent it being marked as 'class_preverified' by Dalvik VM,ART VM don't have this problem),it will solve ur problem!

**Comment by liuyan82** [comment]
> > Now, I faced the same problem as above,can you tell me why and what I should do with it? thanks a lot
> 
> This is usually happened when call Eventbus.register(subscribe)，subscribe Class is belonged to a different dex which is not THE dex Eventbus class belonged to!So you can add Eventbus ref(such as Eventbus.class.getName()) in your subscribe class to prevent it being marked as 'class_preverified' by Dalvik VM,ART VM don't have this problem),it will solve ur problem!

Thanks. Saved my day.

**Comment by juanlabrador** [comment]
@liuyan82  please you can show me how fix that, please!

**Comment by juanlabrador** [comment]
It happens when Dexguard is active, How I can add Eventbus ref in subscribe class?

**Comment by soochun-deali** [comment]
same here with after applying dexguard

**Comment by soochun-deali** [comment]
fix with below rule added

dexguard version : 8.6.06
eventbus version : 3.2.0

-keepnames class org.greenrobot.eventbus.**
-keep class org.greenrobot.eventbus.** { *; }
