### ISSUE TITLE
java.lang.NoClassDefFoundError: org.greenrobot.eventbus.meta.SimpleSubscriberInfo

### ISSUE THREAD

**Issue by felipevaladares** [greenrobot/EventBus#407]
Android 4.4.2 Galaxy Note II (t03g)
I'm getting this error specific on that device and android version, before i was getting: `java.lang.NoClassDefFoundError: org.greenrobot.eventbus`

After changed to the recommended solution of  subscriber index the error changed to:
```
java.lang.NoClassDefFoundError: org.greenrobot.eventbus.meta.SimpleSubscriberInfo
at br.com.bry.brysigner.SignerEventBusIndex.<clinit>(SignerEventBusIndex.java:20)
at br.com.bry.brysigner.AppCache.loadEventBus(AppCache.java:64)
at br.com.bry.brysigner.AppCache.onCreate(AppCache.java:48)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4730)
at android.app.ActivityThread.access$1600(ActivityThread.java:175)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1368)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:146)
at android.app.ActivityThread.main(ActivityThread.java:5602)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
at dalvik.system.NativeStart.main(Native Method)
```

**Comment by greenrobot-team** [comment]
`NoClassDefFoundError` indicates that for some reason this class is not in your final APK. Make sure that you do not have set up ProGuard, or another tool, that strips the EventBus classes from your APK.

Note: You can inspect the classes in your APK by double-clicking it in Android Studio and clicking the `classes.dex` file.
-ut
