### ISSUE TITLE
Eventbus register fails in android 2.3

### ISSUE THREAD

**Issue by martinvandzura** [greenrobot/EventBus#42]
Hi, Eventbus register fails in android 2.3 with exception:
797-797/com.vandzi.eventbustest E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.NoClassDefFoundError: de.greenrobot.event.EventBus
            at com.vandzi.eventbustest.MainActivity.onResume(MainActivity.java:28)
            at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1150)
            at android.app.Activity.performResume(Activity.java:3832)
            at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2110)
            at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2135)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1668)
            at android.app.ActivityThread.access$1500(ActivityThread.java:117)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:931)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:130)
            at android.app.ActivityThread.main(ActivityThread.java:3683)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:507)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
            at dalvik.system.NativeStart.main(Native Method)

You can find example project at https://dl.dropboxusercontent.com/u/58420656/EventbusTestProject.zip

**Comment by martyglaubitz** [comment]
That#s it?! You're just closing this up?!
