### ISSUE TITLE
 java.lang.NoClassDefFoundError: Failed resolution of: Lorg/greenrobot/eventbus/EventBus;

### ISSUE THREAD

**Issue by Daung** [greenrobot/EventBus#438]
java.lang.NoClassDefFoundError: Failed resolution of: Lorg/greenrobot/eventbus/EventBus;
                                                                     at com.qlot.common.base.BaseFragment.f(BaseFragment.java:93)
                                                                     at com.qlot.common.base.BaseFragment.onCreateView(BaseFragment.java:79)
                                                                     at android.support.v4.app.Fragment.performCreateView(Fragment.java:2192)
                                                                     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1299)
                                                                     at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
                                                                     at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:753)
                                                                     at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2363)
                                                                     at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149)
                                                                     at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
                                                                     at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2013)
                                                                     at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388)
                                                                     at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:607)
                                                                     at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1248)
                                                                     at android.app.Activity.performStart(Activity.java:6679)
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2609)
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
                                                                     at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                     at android.os.Looper.loop(Looper.java:154)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
                                                                  Caused by: java.lang.ClassNotFoundException: Didn't find class "org.greenrobot.eventbus.EventBus" on path: DexPathList[[zip file "/data/app/lib.qqb.com.demo1-2/base.apk"],nativeLibraryDirectories=[/data/app/lib.qqb.com.demo1-2/lib/x86, /system/lib, /vendor/lib]]
                                                                     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                     at com.qlot.common.base.BaseFragment.f(BaseFragment.java:93) 
                                                                     at com.qlot.common.base.BaseFragment.onCreateView(BaseFragment.java:79) 
                                                                     at android.support.v4.app.Fragment.performCreateView(Fragment.java:2192) 
                                                                     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1299) 
                                                                     at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528) 
                                                                     at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:753) 
                                                                     at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2363) 
                                                                     at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149) 
                                                                     at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103) 
                                                                     at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2013) 
                                                                     at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388) 
                                                                     at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:607) 
                                                                     at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1248) 
                                                                     at android.app.Activity.performStart(Activity.java:6679) 
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2609) 
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707) 
                                                                     at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460) 
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                     at android.os.Looper.loop(Looper.java:154) 
                                                                     at android.app.ActivityThread.main(ActivityThread.java:6077) 
                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by greenrobot-team** [comment]
Are you using multidex? If yes, [make sure that EventBus is in the primary dex file](https://developer.android.com/studio/build/multidex.html#keep) as it appears it is required for your app to start or turn off multidex if it is not required. -ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut
