### ISSUE TITLE
Could not dispatch event: class to subscribing class and it is showing Null Pointer

### ISSUE THREAD

**Issue by avinashshankar** [greenrobot/EventBus#443]
This is my Subscribe Event:
```
`@Subscribe(threadMode = ThreadMode.MAIN)
    public void stateUpdate(ObdCommandJob job) {
        final String cmdName = job.getCommand().getName();
       cmdResult = "";
        final String cmdID = LookUpCommand(cmdName);
        Log.d(TAG, "stateUpdate() ");
        if (job.getState().equals(ObdCommandJob.ObdCommandJobState.EXECUTION_ERROR)) {
            cmdResult = job.getCommand().getResult();
            if (cmdResult != null && isServiceBound) {
                obdStatusTextView.setText(cmdResult.toLowerCase());
            }
        } else if (job.getState().equals(ObdCommandJob.ObdCommandJobState.BROKEN_PIPE)) {
            if (isServiceBound)
                stopLiveData();
        } else if (job.getState().equals(ObdCommandJob.ObdCommandJobState.NOT_SUPPORTED)) {
            cmdResult = "NA";
        } else {
            cmdResult = job.getCommand().getFormattedResult();
            if (isServiceBound)
                obdStatusTextView.setText("Receiving data...");
        }
        cmdResult.replace("NODATA", "0");
        if (vv.findViewWithTag(cmdID) != null) {
            TextView existingTV = (TextView) vv.findViewWithTag(cmdID);
            existingTV.setText(cmdResult);
        }

    }`  
```

This is my Event Post 
```
`protected void executeQueue() throws InterruptedException {
        Log.d(TAG, "Executing queue..");
        while (!Thread.currentThread().isInterrupted()) {
            ObdCommandJob job = null;
            try {
                job = jobsQueue.take();

                // log job
                Log.d(TAG, "Taking job[" + job.getId() + "] from queue..");

                if (job.getState().equals(ObdCommandJob.ObdCommandJobState.NEW)) {
                    Log.d(TAG, "Job state is NEW. Run it..");
                    job.setState(ObdCommandJob.ObdCommandJobState.RUNNING);
                    if (sock.isConnected()) {
                        job.getCommand().run(sock.getInputStream(), sock.getOutputStream());
                    } else {
                        job.setState(ObdCommandJob.ObdCommandJobState.EXECUTION_ERROR);
                        Log.e(TAG, "Can't run command on a closed socket.");
                    }
                } else
                    // log not new job
                    Log.e(TAG,
                            "Job state was not new, so it shouldn't be in queue. BUG ALERT!");
            } catch (InterruptedException i) {
                Thread.currentThread().interrupt();
            } catch (UnsupportedCommandException u) {
                if (job != null) {
                    job.setState(ObdCommandJob.ObdCommandJobState.NOT_SUPPORTED);
                }
                Log.d(TAG, "Command not supported. -> " + u.getMessage());
            } catch (IOException io) {
                if (job != null) {
                    if(io.getMessage().contains("Broken pipe"))
                        job.setState(ObdCommandJob.ObdCommandJobState.BROKEN_PIPE);
                    else
                        job.setState(ObdCommandJob.ObdCommandJobState.EXECUTION_ERROR);
                }
                Log.e(TAG, "IO error. -> " + io.getMessage());
            } catch (Exception e) {
                if (job != null) {
                    job.setState(ObdCommandJob.ObdCommandJobState.EXECUTION_ERROR);
                }
                Log.e(TAG, "Failed to run command. -> " + e.getMessage());
            }

            ObdCommandJob job2 = job;
            if(job2 !=null)
                EventBus.getDefault().post(job2);
        }
    }`
```

This is in Mainactivity stateUpdate() used in @Subscribe Event Main Thread to update UI.

```
`@Override
    public void stateUpdateinActivity(ObdCommandJob job) {
        tobj = new LiveFragment();
        tobj.stateUpdate(job);
    }`
```

this a logcat
```
`samplersoft.alive D/com.samplersoft.alive.ObdGatewayService: Job state is NEW. Run it..
06-22 13:57:08.940 11768-11768/com.samplersoft.alive E/EventBus: Could not dispatch event: class com.samplersoft.alive.ObdCommandJob to subscribing class class com.samplersoft.alive.LiveFragment
                                                                 java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.replace(java.lang.CharSequence, java.lang.CharSequence)' on a null object reference
                                                                     at com.samplersoft.alive.LiveFragment.stateUpdate(LiveFragment.java:270)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:485)
                                                                     at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:479)
                                                                     at org.greenrobot.eventbus.HandlerPoster.handleMessage(HandlerPoster.java:67)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                     at android.os.Looper.loop(Looper.java:148)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
06-22 13:57:08.940 11768-14522/com.samplersoft.alive E/com.samplersoft.alive.ObdGatewayService: Failed to run command. -> Attempt to invoke virtual method 'boolean android.bluetooth.BluetoothSocket.isConnected()' on a null object reference`
```

**Comment by greenrobot-team** [comment]
Have a look at the error message, here is your issue:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.replace(java.lang.CharSequence, java.lang.CharSequence)' on a null object reference
  at com.samplersoft.alive.LiveFragment.stateUpdate(LiveFragment.java:270)
```

Looks like `cmdResult` can be `null`, so `cmdResult.replace("NODATA", "0");` fails.
-ut
