### ISSUE TITLE
postSingleEvent()--getClass()--NullPointerException

### ISSUE THREAD

**Issue by SuperXpher** [greenrobot/EventBus#466]
When I release an event, the following question arises. After debugging, it was found that once the subscription was made, the error was reported. I publish in the Dialog and subscribe to the event in the Activity. How can I solve this problem?

> FATAL EXCEPTION: main
                                                             Process: com.sdby.bglc, PID: 7954
                                                             java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
                                                                 at org.greenrobot.eventbus.EventBus.postSingleEvent(EventBus.java:363)
                                                                 at org.greenrobot.eventbus.EventBus.post(EventBus.java:251)
                                                                 at com.sdby.bglc.sell.gathering.GatheringDiscountDialog.lambda$getView$1(GatheringDiscountDialog.java:77)
                                                                 at com.sdby.bglc.sell.gathering.GatheringDiscountDialog$$Lambda$4.onClick(Unknown Source)
                                                                 at android.view.View.performClick(View.java:4848)
                                                                 at android.view.View$PerformClick.run(View.java:20262)
                                                                 at android.os.Handler.handleCallback(Handler.java:815)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                 at android.os.Looper.loop(Looper.java:194)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5637)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at java.lang.reflect.Method.invoke(Method.java:372)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by CysionLiu** [comment]
I guess you put null into  EventBus.getDefault().post(...can **not** be null...);

**Comment by SuperXpher** [comment]
@CysionLiu The object is nonempty, and I post objects without a subscription without exception. The problem is that when I subscribe to the message in the Activity, I have an exception for the null pointer. This scenario is a Dialog that sends a message to the Activity, which I've done in a couple of places, but it's not clear why it's here.

**Comment by SuperXpher** [comment]
The error message:
> java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
                                                                   at org.greenrobot.eventbus.EventBus.postSingleEvent(EventBus.java:363)
                                                                   at org.greenrobot.eventbus.EventBus.post(EventBus.java:251)
                                                                   at com.sdby.bglc.sell.gathering.GatheringDiscountDialog.lambda$getView$1(GatheringDiscountDialog.java:78)
                                                                   at com.sdby.bglc.sell.gathering.GatheringDiscountDialog$$Lambda$4.onClick(Unknown Source)
                                                                   at android.view.View.performClick(View.java:4848)
                                                                   at android.view.View$PerformClick.run(View.java:20262)
                                                                   at android.os.Handler.handleCallback(Handler.java:815)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                   at android.os.Looper.loop(Looper.java:194)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5637)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at java.lang.reflect.Method.invoke(Method.java:372)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

There was no mistake last week, and this week began to report the wrong thing. This kind of bug is really a headache.
