### ISSUE TITLE
can´t compile on kitkat but ok on Marshmallow

### ISSUE THREAD

**Issue by erikswed** [greenrobot/EventBus#475]
On the  Samsung Note 4 Android version 6.0.1 it´s working but on a Samsung Tablet Android version 4.4.2 I get this exception:

```
Caused by: org.greenrobot.eventbus.e: 
Subscriber class com.game.android.ui.launcher.DebugViewer$a 
and its super classes have no public methods with the @Subscribe annotation
		at org.greenrobot.eventbus.m.a(SourceFile:67)
		at org.greenrobot.eventbus.c.a(SourceFile:136)
		at com.game.android.ui.launcher.DebugViewer$a.<init>(SourceFile:102)
		at com.game.android.ui.launcher.DebugViewer.setContentView(SourceFile:70)
		at com.game.android.ui.launcher.ActivityMain.onCreate(SourceFile:170)
		at android.app.Activity.performCreate(Activity.java:5541)
		at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
		at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2368)
		at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2464) 
		at android.app.ActivityThread.access$900(ActivityThread.java:172) 
		at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308) 
		at android.os.Handler.dispatchMessage(Handler.java:102) 
		at android.os.Looper.loop(Looper.java:146) 
		at android.app.ActivityThread.main(ActivityThread.java:5653) 
		at java.lang.reflect.Method.invokeNative(Native Method) 
```

This is how I implemented it: Note that I subscribe and register in the nested class only. I removed this subscriber and kept going then same thing happens in Fragment when register subscriber, no public methods error..any ide? . This still works on api 23

```
/**
 * The DebugViewer show real time Firebase asynchronous activity<br>
 */
public abstract class DebugViewer extends BaseActivity {

    private final Object workItemsLock;
    private RecyclerView recyclerView;
    RecyclerViewAdapter adapter;

    public DebugViewer() {
        workItemsLock = new Object();
    }

    @Override
    public void setContentView(@LayoutRes int layoutResID) {
        super.setContentView(layoutResID);
        recyclerView = (RecyclerView) findViewById(R.id.recyclerview);
        adapter = new RecyclerViewAdapter(getApplication());
        recyclerView.setAdapter(adapter);
        recyclerView.setLayoutManager(new LinearLayoutManager(this));
        if (LogManager.isDebugable())
            ((Button) findViewById(R.id.handle)).setVisibility(View.VISIBLE);
    }

    @Override
    protected void onResume() {
        super.onResume();
    }

    @Override
    protected void onPause() {
        super.onPause();
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        adapter.onDestroy();
    }

    private class RecyclerViewAdapter extends RecyclerView.Adapter<ViewHolder> {
        LinkedHashMap<Integer, BaseJob> list;
        Context context;

        public RecyclerViewAdapter(Context context) {
            this.context = context;
            list = MyDatabaseReference.getWorkItems();
            if (!Application.getInstance().getEventBus().isRegistered(this))
                Application.getInstance().getEventBus().register(this);
        }

        @Subscribe(threadMode = ThreadMode.MAIN)
        public void onFireBase(OnFirebaseEvent workItem) {
            synchronized (workItemsLock) {
                boolean found = false;
                notifyItemChanged(workItem.baseJob.listId);
                recyclerView.post(new Runnable() {
                    @Override
                    public void run() {
                        recyclerView.smoothScrollToPosition(adapter.getItemCount());
                    }
                });
            }
        }

        @Override
        public ViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
            View v = LayoutInflater.from(parent.getContext()).inflate(R.layout.list_item_work_item, parent, false);
            return new ViewHolder(v);
        }

        @Override
        public void onBindViewHolder(ViewHolder holder, int position) {
            BaseJob item = list.get(position);
            holder.setWorkItem(item, position);
        }

        @Override
        public int getItemCount() {
            return list.size();
        }

        @Override
        public void onAttachedToRecyclerView(RecyclerView recyclerView) {
            super.onAttachedToRecyclerView(recyclerView);
        }

        public void onDestroy() {
            Application.getInstance().getEventBus().unregister(this);
        }
    }

    static class ViewHolder extends RecyclerView.ViewHolder {
        TextView description;
        TextView listId;
        TextView listenerId;
        TextView listenerType;
        ImageView imageView;
        BaseJob listener;

        ViewHolder(View itemView) {
            super(itemView);
            listenerType = (TextView) itemView.findViewById(R.id.txtListenerType);
            listId = (TextView) itemView.findViewById(R.id.listId);
            description = (TextView) itemView.findViewById(R.id.description);
            listenerId = (TextView) itemView.findViewById(R.id.listenerId);
            imageView = (ImageView) itemView.findViewById(R.id.imageView);
            startBlink();
        }

        public void stopBlink() {
            imageView.clearAnimation();
            imageView.setBackgroundResource(R.drawable.green_cirkel);
        }

        public void setWorkItem(BaseJob listener, int position) {
            this.description.setText(listener.description);
            this.listId.setText(Integer.toString(position));
            this.listenerId.setText(listener.id);
            listenerType.setText(listener.TAG);
            this.listener = listener;
            if (listener.stopped)
                stopBlink();
            else
                imageView.setBackgroundResource(R.drawable.red_cirkel);
        }

        private void startBlink() {
            final Animation animation = new AlphaAnimation((float) 0.5, 0); // Change alpha from fully visible to invisible
            animation.setDuration(100); // duration - half a second
            animation.setInterpolator(new LinearInterpolator()); // do not alter animation rate
            animation.setRepeatCount(Animation.INFINITE); // Repeat animation infinitely
            animation.setRepeatMode(Animation.REVERSE); // Reverse animation at the end so the button will fade back in
            imageView.startAnimation(animation);
        }
    }
}
```

**Comment by greenrobot-team** [comment]
Two things:
- try to make `RecyclerViewAdapter` public.
- it looks like you are using ProGuard: make sure you have added [rules for EventBus](http://greenrobot.org/eventbus/documentation/proguard/).
-ut

**Comment by erikswed** [comment]
I forgot ProGuard rules. Adding that then it works on the Samsung Tablet Android version 4.4.2.
It´s strange how it works on Samsung Note 4 Android version 6.0.1 without ProGuard rules
