### ISSUE TITLE
error in register in api 14 

### ISSUE THREAD

**Issue by atrakidea** [greenrobot/EventBus#494]
# hi , please help me : error in api 14   in  EventBus.getDefault().register(this);   

# please example code for fixed 

`E/UncaughtException: java.lang.NoClassDefFoundError: android/os/PersistableBundle
                                                                        at java.lang.Class.getDeclaredMethods(Native Method)
                                                                        at java.lang.Class.getPublicMethodsRecursive(Class.java:955)
                                                                        at java.lang.Class.getMethods(Class.java:938)
                                                                        at org.greenrobot.eventbus.SubscriberMethodFinder.findUsingReflectionInSingleClass(SubscriberMethodFinder.java:157)
                                                                        at org.greenrobot.eventbus.SubscriberMethodFinder.findUsingInfo(SubscriberMethodFinder.java:88)
                                                                        at org.greenrobot.eventbus.SubscriberMethodFinder.findSubscriberMethods(SubscriberMethodFinder.java:64)
                                                                        at org.greenrobot.eventbus.EventBus.register(EventBus.java:140)
                                                                        at bashirMarket.ir.Activity.MainActivity.onStart(MainActivity.java:282)
                                                                        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1167)
                                                                        at android.app.Activity.performStart(Activity.java:5132)
                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2316)
                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2395)
                                                                        at android.app.ActivityThread.access$600(ActivityThread.java:162)
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:107)
                                                                        at android.os.Looper.loop(Looper.java:194)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5392)
                                                                        at java.lang.reflect.Method.invokeNative(Native Method)
                                                                        at java.lang.reflect.Method.invoke(Method.java:525)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
                                                                        at dalvik.system.NativeStart.main(Native Method)
                                                                     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.os.PersistableBundle" on path: DexPathList[[zip file "/data/app/rezvanoffer.com-2.apk", zip file "/data/data/rezvanoffer.com/code_cache/secondary-dexes/rezvanoffer.com-2.apk.classes2.zip", zip file "/data/data/rezvanoffer.com/code_cache/secondary-dexes/rezvanoffer.com-2.apk.classes3.zip"],nativeLibraryDirectories=[/data/app-lib/rezvanoffer.com-2, /vendor/lib, /system/lib]]
                                                                        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:53)
                                                                        at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
                                                                        at java.lang.ClassLoader.loadClass`

**Comment by atrakidea** [comment]
Fixed / 👍 

i am use Register in fragment 
not use MainActivity register
