### ISSUE TITLE
Crash when calling register()

### ISSUE THREAD

**Issue by liuzhen2008** [greenrobot/EventBus#498]
I get a crash for a missing PersistableBundle for some reason.

This same device is able to run a different app that I know for sure integrate with greenbot eventbus.

The device API level is 19, so it for sure doesn't have PersistableBundle included.

I am wondering what is making eventbus to use that particular class for only my app. But not for the other app.

```
12-06 16:09:46.058 11379-11379/com.myawesome E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.myawesome, PID: 11379
java.lang.NoClassDefFoundError: android/os/PersistableBundle
at java.lang.Class.getDeclaredMethods(Native Method)
at java.lang.Class.getPublicMethodsRecursive(Class.java:894)
at java.lang.Class.getMethods(Class.java:877)
at org.greenrobot.eventbus.SubscriberMethodFinder.findUsingReflectionInSingleClass(SubscriberMethodFinder.java:157)
at org.greenrobot.eventbus.SubscriberMethodFinder.findUsingInfo(SubscriberMethodFinder.java:88)
at org.greenrobot.eventbus.SubscriberMethodFinder.findSubscriberMethods(SubscriberMethodFinder.java:64)
at org.greenrobot.eventbus.EventBus.register(EventBus.java:136)
at com.myawesome.android.view.activity.main.MainActivity.onStart(MainActivity.java:120)

```

**Comment by liuzhen2008** [comment]
I notice that a super class is referencing this class my bad.
