### ISSUE TITLE
org.greenrobot.eventbus.SubscriberMethodFinder$FindState.clazz' on a null object reference

### ISSUE THREAD

**Issue by peach-djf** [greenrobot/EventBus#508]
```
Back traces starts.
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mode.app/com.mode.app.activity.SplashActivity}: java.lang.NullPointerException: Attempt to read from field 'java.lang.Class org.greenrobot.eventbus.SubscriberMethodFinder$FindState.clazz' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2585)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2667)
	at android.app.ActivityThread.-wrap11(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1494)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:5776)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
Caused by: java.lang.NullPointerException: Attempt to read from field 'java.lang.Class org.greenrobot.eventbus.SubscriberMethodFinder$FindState.clazz' on a null object reference
	at org.greenrobot.eventbus.SubscriberMethodFinder.findUsingReflectionInSingleClass(SubscriberMethodFinder.java)
	at org.greenrobot.eventbus.EventBus.getDefault(EventBus.java)
	                                    register
	                           SubscriberMethodFinder.findSubscriberMethods(SubscriberMethodFinder.java)
	                           EventBus.register(EventBus.java)
	                           SubscriberMethodFinder.findUsingReflection(SubscriberMethodFinder.java)
	                                                  findSubscriberMethods
	                           EventBus.register(EventBus.java)
	                           SubscriberMethodFinder.findUsingInfo(SubscriberMethodFinder.java)
	                                                  findSubscriberMethods
	                           EventBus.register(EventBus.java)
	                           SubscriberMethodFinder.getSubscriberInfo(SubscriberMethodFinder.java)
	                                                  findUsingInfo
	                                                  findSubscriberMethods
	                           EventBus.register(EventBus.java)
	                                    subscribe
	                                    checkPostStickyEventToSubscription
	                                    postSingleEventForEventType
	                                    postToSubscription
	                           HandlerPoster.enqueue(HandlerPoster.java)
	                           EventBus.postToSubscription(EventBus.java)
	                           BackgroundPoster.enqueue(BackgroundPoster.java)
	                           EventBus.postToSubscription(EventBus.java)
	                                    getExecutorService
	                           BackgroundPoster.enqueue(BackgroundPoster.java)
	                           EventBus.postToSubscription(EventBus.java)
	                           AsyncPoster.enqueue(AsyncPoster.java)
	                           EventBus.postToSubscription(EventBus.java)
	                                    getExecutorService
	                           AsyncPoster.enqueue(AsyncPoster.java)
	                           EventBus.postToSubscription(EventBus.java)
	                                    lookupAllEventTypes
	                                    addInterfaces
	                                    invokeSubscriber
	at com.mode.app.activity.SplashActivity.onCreate(SplashActivity.java)
	at android.app.Activity.performCreate(Activity.java:6582)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1113)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2532)
	... 9 more

-----------------------------------------------------------------------------------------------
 compile 'org.greenrobot:eventbus:3.0.0'
##--------------- EventBus ------------
-keepclassmembers class ** {
    @org.greenrobot.eventbus.Subscribe <methods>;
}
-keep enum org.greenrobot.eventbus.ThreadMode { *; }

# Only required if you use AsyncExecutor
-keepclassmembers class * extends org.greenrobot.eventbus.util.ThrowableFailureEvent {
    <init>(java.lang.Throwable);
}


--------------------------------------
SplashActivity.java

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_splash);
        EventBus.getDefault().register(this);
   }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        EventBus.getDefault().unregister(this);
    }


    @Subscribe(threadMode = ThreadMode.MAIN)
    public void onDangerous(DangerousEvent event) {
                 //do some th
    }



--------------------------------------------

Lenovo A7010a48

Android 6.0
armeabi-v7a
CPU hardware : mt6735
```

**Comment by greenrobot-team** [comment]
Can you verify the issues also exists with `3.1.1`?

I do not see anything wrong in particular. It would help if you can share a minimal example project that has this issue.
-ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut
