### ISSUE TITLE
[EventBus AndroidX bug] java.lang.NoClassDefFoundError: android.view.textclassifier.TextClassifier

### ISSUE THREAD

**Issue by ParticleCore** [greenrobot/EventBus#569]
Recently migrated to AndroidX and I am now facing this problem that leads to the app crashing

````
03-20 15:49:11.017 12648-12648/com.project.test E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.project.test, PID: 12648
    java.lang.NoClassDefFoundError: android.view.textclassifier.TextClassifier
        at libcore.reflect.InternalNames.getClass(InternalNames.java:55)
        at java.lang.Class.getDexCacheType(Class.java:479)
        at java.lang.reflect.ArtMethod.getDexCacheType(ArtMethod.java:191)
        at java.lang.reflect.ArtMethod.getParameterTypes(ArtMethod.java:136)
        at java.lang.reflect.Method.getParameterTypes(Method.java:174)
        at org.greenrobot.eventbus.SubscriberMethodFinder.findUsingReflectionInSingleClass(SubscriberMethodFinder.java:163)
        at org.greenrobot.eventbus.SubscriberMethodFinder.findUsingInfo(SubscriberMethodFinder.java:88)
        at org.greenrobot.eventbus.SubscriberMethodFinder.findSubscriberMethods(SubscriberMethodFinder.java:64)
        at org.greenrobot.eventbus.EventBus.register(EventBus.java:140)
        at com.project.test.views.CustomTextView.onAttachedToWindow(SystemMessageLayout.java:223)
        at android.view.View.dispatchAttachedToWindow(View.java:13525)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2695)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2695)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2695)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2695)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2695)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2695)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1301)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1063)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5887)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
        at android.view.Choreographer.doCallbacks(Choreographer.java:580)
        at android.view.Choreographer.doFrame(Choreographer.java:550)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.textclassifier.TextClassifier" on path: DexPathList[[zip file "/data/app/com.project.test-2/base.apk"],nativeLibraryDirectories=[/data/app/com.project.test-2/lib/arm, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at libcore.reflect.InternalNames.getClass(InternalNames.java:53)
        at java.lang.Class.getDexCacheType(Class.java:479) 
        at java.lang.reflect.ArtMethod.getDexCacheType(ArtMethod.java:191) 
        at java.lang.reflect.ArtMethod.getParameterTypes(ArtMethod.java:136) 
        at java.lang.reflect.Method.getParameterTypes(Method.java:174) 
        at org.greenrobot.eventbus.SubscriberMethodFinder.findUsingReflectionInSingleClass(SubscriberMethodFinder.java:163) 
        at org.greenrobot.eventbus.SubscriberMethodFinder.findUsingInfo(SubscriberMethodFinder.java:88) 
        at org.greenrobot.eventbus.SubscriberMethodFinder.findSubscriberMethods(SubscriberMethodFinder.java:64) 
        at org.greenrobot.eventbus.EventBus.register(EventBus.java:140) 
        at com.project.test.views.CustomTextView.onAttachedToWindow(SystemMessageLayout.java:223) 
        at android.view.View.dispatchAttachedToWindow(View.java:13525) 
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2695) 
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2695) 
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2695) 
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2695) 
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2695) 
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2695) 
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1301) 
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1063) 
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5887) 
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767) 
        at android.view.Choreographer.doCallbacks(Choreographer.java:580) 
        at android.view.Choreographer.doFrame(Choreographer.java:550) 
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753) 
        at android.os.Handler.handleCallback(Handler.java:739) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5254) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
    	Suppressed: java.lang.ClassNotFoundException: android.view.textclassifier.TextClassifier
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        		... 33 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
````

This is a custom view that extends `AppCompatTextView` (`import androidx.appcompat.widget.AppCompatTextView;`)

I have the following set in `onAttachedToWindow` 

````java
        super.onAttachedToWindow();

        setInitialValues();

        final EventBus eventBus;

        if (!(eventBus = EventBus.getDefault()).isRegistered(this)) {
            eventBus.register(this);
        }
````

That is it, nothing more. As soon as I remove/comment the event bus registration block the app no longer crashes.

There is a `@Subscribe` on the view and it is working perfectly fine before the AndroidX migration.

The proguard rules haven't been changed:

````pro
-keepattributes *Annotation*
-keepclassmembers class ** {
    @org.greenrobot.eventbus.Subscribe <methods>;
}
-keep enum org.greenrobot.eventbus.ThreadMode { *; }
````

I have a different custom view that extends `TabLayout` (`import com.google.android.material.tabs.TabLayout;`) at the same time, using the exact same logic and it is not having any problems, so I assume this is an incompatibility/bug in EventBus with the AndroidX support.

Any advice on what can be done on our end or is this something that needs to be fixed on the library?

**Comment by ParticleCore** [comment]
Forgot to include that I have the following in the gradle

````gradle
            minifyEnabled true
            shrinkResources true
````

**Comment by msoula** [comment]
Hi ParticleCore,
First of all, I'm sorry if my english is not correct.

The TextClassifier class has been refactored in Material library on 1.0.0-alpha02. From this version, the library requires API level 26 to export the class (at least, that is what I understand).
So if you're working on a system whose API level is below 26, the reflection process which is done by the EventBus library will fail right now.

I had the same problem and my solution was to downgrade material library version to 1.0.0-alpha01.

**Comment by ParticleCore** [comment]
@msoula I can see that the `TextClassifier` was made available in [API 26](https://developer.android.com/reference/android/view/textclassifier/TextClassifier), just like you said. However, I cannot downgrade the library since it contains fixes in the latest versions that I require, so that workaround will not work for me.

Thanks for the explanation and the workaround suggestion.

**Comment by msoula** [comment]
Otherwise, if you may just have to set minSdkVersion to 26.
I can do that on my app since it has to work on API level 24 :/

**Comment by ParticleCore** [comment]
@msoula Not an option for me either, I have to stick with min API 21, but thank you.

**Comment by greenrobot-team** [comment]
@msoula Thanks for answering. This is also mentioned in the FAQ.
http://greenrobot.org/eventbus/documentation/faq/#Troubleshooting

-Uwe
