### ISSUE TITLE
Crashlytic report on my project. Please support to solve. Tks.

### ISSUE THREAD

**Issue by ttsang** [greenrobot/EventBus#583]
Fatal Exception: org.greenrobot.eventbus.EventBusException: Subscriber class notification.NotificationDetailFragment and its super classes have no public methods with the @Subscribe annotation
       at org.greenrobot.eventbus.SubscriberMethodFinder.findSubscriberMethods(SubscriberMethodFinder.java:67)
       at org.greenrobot.eventbus.EventBus.register(EventBus.java:140)
       at notification.NotificationDetailFragment.onStart(NotificationDetailFragment.java:292)
       at android.support.v4.app.Fragment.performStart(Fragment.java:2372)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1467)
       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
       at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3244)
       at android.support.v4.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:3206)
       at android.support.v4.app.FragmentController.dispatchStart(FragmentController.java:206)
       at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:605)
       at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
       at activities.MainActivity.onStart(MainActivity.java:288)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1419)
       at android.app.Activity.performStart(Activity.java:7462)
       at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3388)
       at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
       at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2155)
       at android.os.Handler.dispatchMessage(Handler.java:109)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:7539)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)

**Comment by greenrobot-team** [comment]
The issue is: `Subscriber class notification.NotificationDetailFragment and its super classes have no public methods with the @Subscribe annotation`
http://greenrobot.org/eventbus/documentation/how-to-get-started/#Step_2_Prepare_subscribers

-Uwe
