### ISSUE TITLE
just like this 

### ISSUE THREAD

**Issue by zs1973** [greenrobot/EventBus#590]
I have a baseFragment  and into it I have calle EventBus...register and unregister ,but when I run App on my Test phone  , it is not work.

----------------------------------------Error info------------------------------------------------------
07-06 02:33:51.443 20694-20694/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ofu.qq, PID: 20694
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ofu.qq/com.ofu.qq.ui.login.LoginActivity}: org.greenrobot.eventbus.EventBusException: Subscriber class com.ofu.qq.ui.login.LoginFragment and its super classes have no public methods with the @Subscribe annotation
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3253)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349)
        at android.app.ActivityThread.access$1100(ActivityThread.java:221)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:158)
        at android.app.ActivityThread.main(ActivityThread.java:7224)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
     Caused by: org.greenrobot.eventbus.EventBusException: Subscriber class com.ofu.qq.ui.login.LoginFragment and its super classes have no public methods with the @Subscribe annotation
        at org.greenrobot.eventbus.SubscriberMethodFinder.findSubscriberMethods(SubscriberMethodFinder.java:67)
        at org.greenrobot.eventbus.EventBus.register(EventBus.java:140)
        at com.ofu.qq.base.BaseFragment.onCreate(BaseFragment.java:48)
        at android.support.v4.app.Fragment.performCreate(Fragment.java:2414)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1418)
        at android.support.v4.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1195)
        at android.support.v4.app.FragmentTransition.calculateFragments(FragmentTransition.java:1078)
        at android.support.v4.app.FragmentTransition.startTransitions(FragmentTransition.java:117)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2408)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3273)
        at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3229)
        at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
        at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:620)
        at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1265)
        at android.app.Activity.performStart(Activity.java:6915)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3216)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349) 
        at android.app.ActivityThread.access$1100(ActivityThread.java:221) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:158) 
        at android.app.ActivityThread.main(ActivityThread.java:7224) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
07-06 02:33:52.603 20694-20694/com.ofu.qq I/Process: Sending signal. PID: 20694 SIG: 9
-----------------------------------------my base fragment---------------------------------
public abstract class BaseFragment extends QMUIFragment {

    /**
     * QMUIWindowInsetLayout继承自FrameLayout
     */
    protected FrameLayout rootView;
    protected BaseFragmentActivity activity;
    protected Unbinder unbinder;
    protected QMUITipDialog loadingDialog;
    protected QMUITipDialog normalDialog;

    private BasePresenter mPresenter;
    private BaseFragment mCurrentFragment;

    @Override
    public void onAttach(Context context) {
        super.onAttach(context);
        activity = (BaseFragmentActivity) context;
    }

    @Override
    public void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        EventBus.getDefault().register(this);
        XLog.log(Log.INFO, "-------fragment " + this.getClass().getSimpleName() + "被创建------");
        initData();
        mPresenter = getPresenter();

    }

    @Override
    protected View onCreateView() {
        rootView = (FrameLayout) LayoutInflater.from(getContext()).inflate(getLayoutId(), null);
        unbinder = ButterKnife.bind(this, rootView);
        initView();
        return rootView;
    }

    protected abstract int getLayoutId();

    protected abstract void initData();

    protected abstract void initView();

    protected abstract BasePresenter getPresenter();

    @Override
    public void onStop() {
        super.onStop();
    }

    @Override
    public void onDestroy() {
        super.onDestroy();
        if (null != unbinder) {
            unbinder.unbind();
            XLog.tag("---------").i(this.getClass().getSimpleName() + "ButterKnife unbind");
        }
        //取消订阅
        if (mPresenter != null) {
            mPresenter.unsubscribe();
            XLog.tag("---------").i(this.getClass().getSimpleName() + "------订阅回收-----");
        } else {
            XLog.tag("--------").i("----------没回收----------");
        }
        //关闭Dialog  防止内存泄漏
        dismissLoadingDialog();
        if(null!=normalDialog&&normalDialog.isShowing()){
            normalDialog.dismiss();
        }
        //取消EventBus订阅
        EventBus.getDefault().unregister(this);

    }

    /**
     * 切换Fragment
     *
     * @param resView
     * @param targetFragment
     */
    public void changeFragment(int resView, @NonNull BaseFragment targetFragment) {
        if (targetFragment.equals(mCurrentFragment)) {
            return;
        }
        android.support.v4.app.FragmentTransaction transaction = activity.getSupportFragmentManager().beginTransaction();
        if (!targetFragment.isAdded()) {
            transaction.add(resView, targetFragment, targetFragment.getClass().getName());
        }
        if (targetFragment.isHidden()) {
            transaction.show(targetFragment);
            //targetFragment.onFragmentShow();
        }
        if (mCurrentFragment != null && mCurrentFragment.isVisible()) {
            transaction.hide(mCurrentFragment);
            //mCurrentFragment.onFragmentHide();
        }
        mCurrentFragment = targetFragment;
        transaction.commitAllowingStateLoss();
    }

    protected void showLoadingDialog(String title) {
        loadingDialog = new QMUITipDialog.Builder(activity)
                .setTipWord(title)
                .setIconType(QMUITipDialog.Builder.ICON_TYPE_LOADING)
                .create();

        loadingDialog.show();
    }

    protected void dismissLoadingDialog() {
        if (null != loadingDialog && loadingDialog.isShowing()) {
            loadingDialog.dismiss();
        }
    }

    protected void showNormalDialog(String title) {
        normalDialog = new QMUITipDialog.Builder(activity)
                .setTipWord(title)
                .setIconType(QMUITipDialog.Builder.ICON_TYPE_NOTHING)
                .create();
        normalDialog.show();
        new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    Thread.sleep(1000);
                    normalDialog.dismiss();
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
            }
        }).start();
    }
}

**Comment by d745282469** [comment]
你这个类没有写接收事件的方法，注意错误信息中提示的注解@subscribe

**Comment by greenrobot-team** [comment]
As @d745282469 indicated, your fragment is missing a method annotated with `@Subscribe`.
https://github.com/greenrobot/EventBus#eventbus-in-3-steps
