### ISSUE TITLE
 java.lang.NoClassDefFoundError: android/app/NotificationChannel

### ISSUE THREAD

**Issue by arjinmc** [greenrobot/EventBus#591]
Hey guys, I has a  service to start foreground so that I have a NotificationChannel for android O above. I register Evenbus in the Service.onCreate(). When I run with android L, it crashes like this.

`07-09 15:59:38.632 7563-7563/packageNamexxxxxxx E/AndroidRuntime: FATAL EXCEPTION: main
    Process: packageNamexxxxxxx, PID: 7563
    java.lang.NoClassDefFoundError: android/app/NotificationChannel
        at java.lang.Class.getDeclaredMethods(Native Method)
        at java.lang.Class.getPublicMethodsRecursive(Class.java:894)
        at java.lang.Class.getMethods(Class.java:877)
        at org.greenrobot.eventbus.SubscriberMethodFinder.findUsingReflectionInSingleClass(SubscriberMethodFinder.java:157)
        at org.greenrobot.eventbus.SubscriberMethodFinder.findUsingInfo(SubscriberMethodFinder.java:88)
        at org.greenrobot.eventbus.SubscriberMethodFinder.findSubscriberMethods(SubscriberMethodFinder.java:64)
        at org.greenrobot.eventbus.EventBus.register(EventBus.java:140)
        at packageNamexxxxxxx.KeepAliveService.onCreate(KeepAliveService.java:45)`

**Comment by greenrobot-team** [comment]
The `NotificationChannel` class is not available on devices running Android L or lower, hence the crash.

Some workarounds are mentioned in the FAQ.
http://greenrobot.org/eventbus/documentation/faq/

Notably: try to use a subscriber index which prevents EventBus from using reflection to look up `@Subscribe` methods.
http://greenrobot.org/eventbus/documentation/subscriber-index/

**Comment by arjinmc** [comment]
Yes,I won't use it with NotificationChannel in the same class.
