### ISSUE TITLE
Subscriber class c.b.a.d.c.b.r and its super classes have no public methods with the @Subscribe annotation

### ISSUE THREAD

**Issue by saravanan72** [greenrobot/EventBus#616]
When i used to start with onresume,

@Override
    public void onResume() {
        super.onResume();
        EventBus.getDefault().register(this);
    }

it shot the error like,

h.a.a.e: Subscriber class c.b.a.d.c.b.r and its super classes have no public methods with the @Subscribe annotation
        at h.a.a.p.a(:67)
        at h.a.a.c.c(:140)
        at c.b.a.d.c.b.r.onResume(:374)
        at androidx.fragment.app.Fragment.performResume(:2713)
        at androidx.fragment.app.l.a(:1388)
        at androidx.fragment.app.l.j(:1642)
        at androidx.fragment.app.l.i(:1736)
        at androidx.fragment.app.l.a(:1800)
        at androidx.fragment.app.a.e(:446)
        at androidx.fragment.app.l.a(:2584)
        at androidx.fragment.app.l.b(:2372)
        at androidx.fragment.app.l.c(:2327)
        at androidx.fragment.app.l.c(:2230)
        at androidx.fragment.app.l$c.run(:414)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:7325)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by SaeedJinat** [comment]
that's why : 

if (ignoreGeneratedIndex) {
            subscriberMethods = findUsingReflection(subscriberClass);
        } else {
            subscriberMethods = findUsingInfo(subscriberClass);
        }
        if (subscriberMethods.isEmpty()) {
            throw new EventBusException("Subscriber " + subscriberClass
                    + " and its super classes have no public methods with the @Subscribe annotation");
        } 

if you register to  Eventbus  and couldnt find any of its annotated @subscibe methods , 
it will terminate with the message mentioned above . 


solution :
 1- use  method with @subscriber annotion for your events . 
2- dont forget to unregister .

**Comment by Duna** [comment]
R8 issue #625

**Comment by benjabrons09** [comment]
Same problem relative to R8 here

**Comment by Duna** [comment]
#638

**Comment by misbachulmunir** [comment]
add this on build  buildTypes {
   debug {
     proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
   }
}

**Comment by greenrobot-team** [comment]
Closing as no response and likely duplicate of #586.

Side-note: we are using EventBus in an Android project with latest Android tooling, including R8 without issues. Since the latest release also embeds R8 rules this hopefully should no longer be an issue.
https://github.com/greenrobot/EventBus/blob/master/eventbus-android/consumer-rules.pro
