### ISSUE TITLE
android.app.Activity[] cannot be cast to java.lang.reflect.Method

### ISSUE THREAD

**Issue by arronvera** [greenrobot/EventBus#666]
when I register the eventbus，I met the exception “android.app.Activity[] cannot be cast to java.lang.reflect.Method”

**Comment by arronvera** [comment]
if (!EventBus.getDefault().isRegistered(this)) {
            EventBus.getDefault().register(this);
 }

**Comment by andob** [comment]
any stacktrace of that exception?

**Comment by arronvera** [comment]
java.lang.RuntimeException:Unable to start activity ComponentInfo{LauncherActivity}: java.lang.ClassCastException: android.content.Context[] cannot be cast to java.lang.reflect.Method

**Comment by arronvera** [comment]
Caused by:
5	java.lang.ClassCastException:android.content.Context[] cannot be cast to java.lang.reflect.Method
6	java.lang.reflect.Method$1.compare(Method.java:67)
7	java.util.TimSort.countRunAndMakeAscending(TimSort.java:360)
8	java.util.TimSort.sort(TimSort.java:234)
9	java.util.Arrays.sort(Arrays.java:1492)
10	java.util.ArrayList.sort(ArrayList.java:1470)
11	java.util.Collections.sort(Collections.java:208)
12	libcore.util.CollectionUtils.removeDuplicates(CollectionUtils.java:86)
13	java.lang.Class.getMethods(Class.java:1493)
14	g.a.a.k.a(SubscriberMethodFinder.java:10)
15	g.a.a.c.a(EventBus.java:2)
16	g.a.a.c.c(EventBus.java:1)
17	LauncherActivity.onCreate(Native Method)
18	android.app.Activity.performCreate(Activity.java:8085)
19	android.app.Activity.performCreate(Activity.java:8073)
20	android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1320)

**Comment by arronvera** [comment]
Caused by: java.lang.ClassCastException: android.app.Activity[] cannot be cast to java.lang.reflect.Method
        at java.lang.reflect.Method$1.compare(Method.java:67)
        at java.util.TimSort.binarySort(TimSort.java:296)
        at java.util.TimSort.sort(TimSort.java:239)
        at java.util.Arrays.sort(Arrays.java:1492)
        at java.util.ArrayList.sort(ArrayList.java:1470)
        at java.util.Collections.sort(Collections.java:208)
        at libcore.util.CollectionUtils.removeDuplicates(CollectionUtils.java:86)
        at java.lang.Class.getMethods(Class.java:1493)
        at de.greenrobot.event.SubscriberMethodFinder.findSubscriberMethods(SubscriberMethodFinder.java:55)
        at de.greenrobot.event.EventBus.register(EventBus.java:186)
        at de.greenrobot.event.EventBus.register(EventBus.java:140)

**Comment by greenrobot-team** [comment]
Hm, thanks for reporting. But couldn't find any known issue.

Can you provide a small example to reproduce this?
